/* 
 * File:   main.cpp
 * Author: Jose Lopez
 * Purpose: Find the price of tickets -Total
 * Created on January 15, 2015, 1:38 PM
 */

//System Libraries
#include <iostream>
#include <iomanip>
using namespace std;

//User Libraries

//Global Constants

//Function Prototypes

//Execution begins here!
int main(int argc, char** argv) {
    cout<<fixed;
    cout<<setprecision(2);
    //Declare variables
    float clsA=15.00;
    float clsB=12.00;
    float clsC=9.00;
    int tcktA,tcktB,tcktC;
    //Output program inputs
    cout<<"This program is used to find the money "<<endl;
    cout<<"generated of class A,B and C tickets."<<endl;
    cout<<endl;
    cout<<"How many class A tickets were purchased?"<<endl;
    cin>>tcktA;
    cout<<"How many class B tickets were purchased?"<<endl;
    cin>>tcktB;
    cout<<"How many class C tickets were purchased?"<<endl;
    cin>>tcktC;
    //Perform calculations
    float ttlCst=(clsA*tcktA)+(clsB*tcktB)+(clsC*tcktB);
    //Output results
    cout<<"The total money generated by the purchased tickets was $"<<ttlCst<<endl;
    return 0;
}

