/* 
 * File:   main.cpp
 * Author: Jose Lopez
 * Purpose: Predict the amount that East Coast will generate
 * Created on January 8, 2015, 1:27 PM
 */

//System Libraries
#include <iostream>
#include <iomanip>
using namespace std;

//User Libraries

//Global Constant
const char CONVPCT=100;//Percent Conversion
//Working Prototypes

//Execution begins here!
int main(int argc, char** argv) {
    setprecision(8);
    //Declare variables
    short perTS=58;
    int TtSls=8.6e6;
    //Calculate the problem
    int ECG=perTS*TtSls/CONVPCT;//ECG is how much was generated
    //State program purpose
    cout<<"This program is to identify how much East Coast will generate"<<endl;
    cout<<"with the given Total Sales and Percent Total Sales."<<endl;
    //Output results
    cout<<"The amount that was generated by East Coast was $"<<ECG<<"."<<endl;   
    return 0;
}

